### PR TITLE
Form Validations - Login / Signup

### PR DESCRIPTION
**Pull request by mitpancholi98**
### Changes

- Added [yup schema validator](https://www.npmjs.com/package/yup) and [react-hook-form](https://react-hook-form.com/).
- Created component handler with error messages.
- Added validations for login and sign up page.
- Tweaked classes for better adjustments.
- Removed warnings from terminal.

### Screenshots
image
image
image

Lots of changes! 😃

### CODE REVIEW

**Comment by kankenny** [comment]
@mitpancholi98 This is great and very much appreciated! 

However, my colleague @rintendou and I are wondering why the yup schema replaces firebase? I apologize for the question as I have not encountered yup and I only thought that is a library for user input validations.

**Comment by mitpancholi98** [comment]
Thanks !

Yup does not replace firebase schema. It builds schema for input validation. This way it decouples validation logic and we don't have to write conditional JS in between. You are right that it validates input (Can be anything as an input but preferably object). Yup is a great option in this regard, however there are other alternatives such as hapi, joi.

**Comment by mitpancholi98** [comment]
Oh I see what you are mentioning, that `signUpSchema` and `loginSchema` are just for the form, nothing to do with firebase ✌🏼

**Review by kankenny — APPROVED** [review]

**Review by kankenny — APPROVED** [review]
I tested that the react hook form and yup were not in conflict with anything. The app still has the same functionalities but with extra features like user input validation.

**Comment by kankenny** [comment]
@mitpancholi98 Hi there, I tested your code, and I think your implementation of other tools for this issue is substantial. I have reviewed and approved your code. 

However, I still need my colleague to review on his end to finalize this merge.

**Comment by mitpancholi98** [comment]
> 

Ok no problem ...

**Pull request merged**
